version: 2.1
description: es-helper orb

executors:
  es-helper:
    docker:
      - image: harbor.bestsellerit.com/library/es-helper:v0.0.0


jobs:
  check-kube-config:
    description: Check for deprecated api specs and validates kubernetes yaml
    executor: es-helper
    parameters:
      path:
        description: path to kube spec files
        type: string
      kubernetes_version:
        description: kubernetes major version to check eg. 1.16
        type: string
    steps:
      - checkout
      - run:
          name: check for depracted kubernetes APIs
          command: |
            conftest test << parameters.path >> -p /policies/
      - run:
          name: validate kubernetes config
          command: |
            kubeval << parameters.path >> --strict --kubernetes-version << parameters.kubernetes_version >>.0

commands:
  check-kube-config:
    description: Check for deprecated api specs and validates kubernetes yaml
    parameters:
        path:
          description: path to kube spec files
          type: string
    steps:
      - run:
          name: check for depracted kubernetes APIs
          command: |
            VERSION=0.19.0
            wget https://github.com/instrumenta/conftest/releases/download/v$VERSION/conftest_$VERSION_Linux_x86_64.tar.gz
            tar xzf conftest_$VERSION_Linux_x86_64.tar.gz
            chmod +x conftest
            wget -O - https://github.com/swade1987/deprek8ion/archive/master.tar.gz | tar -xz --strip=1 "deprek8ion-master/policies"
            ./conftest test << parameters.path >> -p ./policies/
      - run:
          name: validate kubernetes config
          command: |
            wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
            tar xf kubeval-linux-amd64.tar.gz
            chmod +x kubeval
            ./kubeval << parameters.path >>
