version: 2.1

executors:
  es-helper:
    docker:
      - image: eu.gcr.io/swade1987/kubernetes-toolkit:1.17.2

jobs:
  check-kube-config:
    description: Check for deprecated api specs and validates kubernetes yaml
    executor: es-helper
    parallelism: 2
    parameters:
      path:
        description: path to kube spec files
        type: string
      kubernetes_version:
        description: kubernetes major version to check eg. 1.16
        type: string
    steps:
      - checkout
      - run:
          name: check for depracted kubernetes APIs
          command: |
            conftest test << parameters.path >> -p /policies/
      - run:
          name: validate kubernetes config
          command: |
            kubeval << parameters.path >> --strict --kubernetes-version << parameters.kubernetes_version >>.0

workflows:
  test:
    jobs:
      - check-kube-config:
          path: ./ingress.yaml ./ingress_valid.yaml
          kubernetes_version: "1.17"
  # publish:
  #   jobs:
  #     - publish:
  #         filters:
  #           tags:
  #             only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  #           branches:
  #             ignore: /.*/