version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable-git
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

  circleci-cli:
    docker:
      - image: circleci/circleci-cli:alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

orbs:
  secret-injector: bestsellerit/secret-injector@1.0.6

jobs:
  test:
    description: validate the orb
    executor: circleci-cli
    steps:
      - checkout
      - run:
          name: validate orb
          command: |
            circleci orb validate ./orb.yml


  docker-build:
    description: Check for deprecated api specs and validates kubernetes yaml
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Push and build image
          command: |
            source /tmp/secrets
            docker login -u $docker_eshelper_username -p $docker_eshelper_password $K8S_CLUSTER_docker_registry_url
            docker build \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest \
              .
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest

  publish:
    description: Check for deprecated api specs and validates kubernetes yaml
    executor: circleci-cli
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - secret-injector/vault-login
      - run:
          name: Replace version
          command: |
            sed -ie 's/CIRCLE_TAG/'"$CIRCLE_TAG"'/g' orb.yml
      - run:
          name: Publish CircleCI orb
          command: |
            export CIRCLECI_CLI_TOKEN=$(vault kv get -field=circleci_token ES/harpocrates)
            CC_NAMESPACE=bestsellerit
            ORB_PATH=./orb.yml
            ORB_NAME=es-helper
            
            circleci orb validate $ORB_PATH
            circleci orb publish $ORB_PATH $CC_NAMESPACE/$ORB_NAME@$CIRCLE_TAG
            circleci orb unlist $CC_NAMESPACE/$ORB_NAME true


workflows:
  test:
    jobs:
      - test
      
  publish:
    jobs:
      - secret-injector/dump-secrets:
          context:
            - es02-prod
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - secret-injector/dump-secrets:
          name: secret-injector/eshelper
          vault-path: ES/data/service_accounts/harbor/eshelper-ci
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - docker-build:
          context:
            - shared
          requires:
            - secret-injector/eshelper
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - publish:
          context:
            - shared
          requires:
            - docker-build
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/